class Rotar(private val indexMap: Map<Char, Int>, private val dataArr: Array<Char>, private var pos: Int) {

    //region CREATING DEFAULT ROTAR

    companion object {
        val rotars = arrayOf(
            Pair(
                mapOf(
                    Pair('v', 8),
                    Pair('c', 4),
                    Pair('f', 3),
                    Pair('j', 13),
                    Pair('k', 17),
                    Pair('z', 15),
                    Pair('g', 20),
                    Pair('u', 11),
                    Pair('w', 24),
                    Pair('t', 22),
                    Pair('o', 18),
                    Pair('r', 21),
                    Pair('l', 6),
                    Pair('i', 7),
                    Pair('q', 16),
                    Pair('e', 9),
                    Pair('a', 25),
                    Pair('n', 23),
                    Pair('d', 10),
                    Pair('s', 1),
                    Pair('x', 5),
                    Pair('m', 0),
                    Pair('h', 14),
                    Pair('y', 2),
                    Pair('b', 12),
                    Pair('p', 19)
                ), arrayOf(
                    'q',
                    'n',
                    'c',
                    'f',
                    'g',
                    'a',
                    'h',
                    'v',
                    't',
                    's',
                    'i',
                    'r',
                    'k',
                    'm',
                    'z',
                    'e',
                    'y',
                    'w',
                    'x',
                    'p',
                    'j',
                    'd',
                    'b',
                    'o',
                    'l',
                    'u'
                )
            ), Pair(
                mapOf(
                    Pair('j', 23),
                    Pair('t', 5),
                    Pair('f', 3),
                    Pair('w', 7),
                    Pair('m', 24),
                    Pair('b', 10),
                    Pair('h', 22),
                    Pair('c', 1),
                    Pair('q', 18),
                    Pair('k', 17),
                    Pair('x', 16),
                    Pair('e', 4),
                    Pair('g', 20),
                    Pair('r', 15),
                    Pair('u', 19),
                    Pair('y', 13),
                    Pair('v', 11),
                    Pair('l', 12),
                    Pair('n', 14),
                    Pair('z', 9),
                    Pair('a', 8),
                    Pair('p', 0),
                    Pair('i', 25),
                    Pair('s', 6),
                    Pair('o', 2),
                    Pair('d', 21)
                ), arrayOf(
                    'e',
                    'w',
                    'n',
                    'a',
                    's',
                    'b',
                    'y',
                    'x',
                    'h',
                    'z',
                    'f',
                    'p',
                    'l',
                    'u',
                    't',
                    'c',
                    'g',
                    'k',
                    'r',
                    'j',
                    'o',
                    'd',
                    'm',
                    'i',
                    'q',
                    'v'
                )
            ), Pair(
                mapOf(
                    Pair('z', 17),
                    Pair('h', 13),
                    Pair('v', 5),
                    Pair('s', 9),
                    Pair('n', 0),
                    Pair('w', 25),
                    Pair('m', 22),
                    Pair('b', 7),
                    Pair('c', 14),
                    Pair('u', 11),
                    Pair('y', 16),
                    Pair('p', 21),
                    Pair('f', 12),
                    Pair('a', 4),
                    Pair('k', 1),
                    Pair('i', 8),
                    Pair('g', 24),
                    Pair('t', 6),
                    Pair('j', 2),
                    Pair('l', 15),
                    Pair('r', 18),
                    Pair('o', 3),
                    Pair('q', 10),
                    Pair('d', 19),
                    Pair('e', 23),
                    Pair('x', 20)
                ), arrayOf(
                    'v',
                    'l',
                    'a',
                    'm',
                    't',
                    'k',
                    'p',
                    'u',
                    's',
                    'z',
                    'j',
                    'c',
                    'o',
                    'b',
                    'n',
                    'r',
                    'f',
                    'g',
                    'y',
                    'q',
                    'x',
                    'e',
                    'i',
                    'w',
                    'h',
                    'd'
                )
            ), Pair(
                mapOf(
                    Pair('w', 11),
                    Pair('t', 13),
                    Pair('m', 0),
                    Pair('l', 23),
                    Pair('p', 7),
                    Pair('q', 25),
                    Pair('u', 14),
                    Pair('y', 20),
                    Pair('s', 17),
                    Pair('z', 16),
                    Pair('x', 5),
                    Pair('d', 21),
                    Pair('b', 2),
                    Pair('n', 15),
                    Pair('j', 19),
                    Pair('r', 3),
                    Pair('o', 6),
                    Pair('f', 12),
                    Pair('i', 4),
                    Pair('c', 10),
                    Pair('k', 18),
                    Pair('e', 8),
                    Pair('g', 24),
                    Pair('v', 22),
                    Pair('a', 9),
                    Pair('h', 1)
                ), arrayOf(
                    'g',
                    'j',
                    'e',
                    'r',
                    'm',
                    'n',
                    'a',
                    'q',
                    'p',
                    'v',
                    'd',
                    'l',
                    'c',
                    'o',
                    'i',
                    'b',
                    'h',
                    'y',
                    'u',
                    'x',
                    'f',
                    'w',
                    'z',
                    's',
                    'k',
                    't'
                )
            ), Pair(
                mapOf(
                    Pair('g', 9),
                    Pair('i', 12),
                    Pair('c', 8),
                    Pair('b', 3),
                    Pair('l', 25),
                    Pair('v', 14),
                    Pair('e', 7),
                    Pair('a', 20),
                    Pair('s', 1),
                    Pair('j', 19),
                    Pair('k', 15),
                    Pair('h', 6),
                    Pair('d', 17),
                    Pair('o', 21),
                    Pair('z', 23),
                    Pair('f', 5),
                    Pair('p', 22),
                    Pair('t', 10),
                    Pair('m', 18),
                    Pair('r', 0),
                    Pair('y', 2),
                    Pair('w', 4),
                    Pair('x', 13),
                    Pair('u', 16),
                    Pair('n', 24),
                    Pair('q', 11),
                ),
                arrayOf(
                    'l',
                    'k',
                    'r',
                    'u',
                    'c',
                    'i',
                    'g',
                    'j',
                    'q',
                    's',
                    'v',
                    'n',
                    'y',
                    'z',
                    'a',
                    'x',
                    't',
                    'f',
                    'd',
                    'o',
                    'b',
                    'm',
                    'e',
                    'h',
                    'w',
                    'p'
                )
            )
        )

    }

    //endregion CREATING DEFAULT ROTAR

    fun rotate(c: Char): Char {
        return dataArr[((indexMap[c]!! + pos++) % 26)]
    }
}